name: "Nexentro Blinds Actuator"
packageKey: "nexentro-blinds-actuator"
permissions:
  zigbee: {}
description: "Supports Nexentro Blinds Actuator"
vendorSupportInformation: "https://community.smartthings.com"
